### ISSUE TITLE
Example of using in project

### ISSUE THREAD

**Issue by kele6ra** [rsispal/srecord-js#1]
Hello, could you help me with using s19reader in project. I have installed packet with npm and how could I use it in project?

**Comment by kele6ra** [comment]
import { readS19 } from '@rsispal/srecord-js';

let srec = readS19(text, size);

**Comment by rsispal** [comment]
A quick note that I'll be replacing this package with a revised version.

Will be at this exact same url `https://github.com/rsispal/srecord-js`
